### PR TITLE
CCET 337 convert sphinx documentation to astrodocs

### PR DESCRIPTION
**Pull request by stephenheg**
## Description
Convert the current sphinx documentation to astrodocs for github pages

## Motivation and Context
Convert the documentation so that is in best practise with other company repos - [Jira Ticket](https://confluentinc.atlassian.net/browse/CCET-337)

PS. README improvements will addressed fully in a seperate ticket - [Jira Ticket]()

## How Has This Been Tested?
Validated manually using documentation of astrodocs to run documentation locally (See screenshots for proof)

## Screenshots (if appropriate):
AWS Secret provider docs

intro docs

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by ddonaghy-c** [comment]
Do we need to make plugins and legal capitalized? on the breadcrumb trail to the left on the main page?

**Comment by ddonaghy-c** [comment]
hmm wondering if we need to convert the directories to uppercase as well so they resolve - tried viewing these and they don't have any files under them 🤔

**Review by ddonaghy-c — APPROVED** [review]
LGTM

**Review by eddyv — APPROVED** [review]
Looks fine at first glance. Here are some improvements you could make in another PR.

1. Set property collapsed on guides / plugins since it takes up a fair amount of real estate.

```
{
        label: 'Guides',
        autogenerate: {
          directory: 'guides',
          collapsed: true
        }
      }
```

2. Configurations could be listed as a sidebar item. Instead of placing them in codeblocks, use headers. Play around with the `maxHeadingLevel` setting to suit your needs.

**Pull request merged**
